spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hackathon?createDatabaseIfNotExist=true
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5120MB
      max-request-size: 5120MB
